version: '3'

services:
  api:
    build: ./api
    ports:
      - "8080:8080"
    networks:
      - backend
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - api
    networks:
      - backend

networks:
  backend:
